development:
  adapter: postgresql
  encoding: unicode
  database: tuner_app_development
  pool: 5
  username: michaelmuse
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: tuner_app_test
  pool: 5
  username: michaelmuse
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tuner_app_production
  pool: 5
  username: michaelmuse
  password:
